---
abstract: 'Dispatch requests to CGI::Snapp-based objects'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Snapp-Dispatch
provides:
  CGI::Snapp::Dispatch:
    file: lib/CGI/Snapp/Dispatch.pm
    version: 1.03
  CGI::Snapp::Dispatch::Regexp:
    file: lib/CGI/Snapp/Dispatch/Regexp.pm
    version: 1.03
requires:
  CGI::Snapp: 1.03
  Capture::Tiny: 0.16
  Carp: 1.2
  Class::Load: 0.18
  File::Spec: 0.86
  HTTP::Exception: 0.04001
  Hash::FieldHash: 0.1
  IO::Pipe: 1.14
  Log::Handler: 0.75
  Proc::Fork: 0.71
  Try::Tiny: 0.11
  parent: 0.225
  strict: 1.03
  warnings: 1.03
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 1.03
